# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install NuGet CLI
      run: sudo apt-get install -y nuget
    - name: Restore dependencies
      run: dotnet restore Reborn.IdentityServer4.Admin.sln
    - name: Build
      run: dotnet build Reborn.IdentityServer4.Admin.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Reborn.IdentityServer4.Admin.sln --configuration Release --no-build
    - name: Pack using .nuspec
      run: nuget pack ./templates/template-build/Reborn.IdentityServer4.Admin.Templates.nuspec -NoDefaultExcludes -OutputDirectory ./nupkg
    - name: Publish to NuGet
      run: nuget push ./nupkg/*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source "https://api.nuget.org/v3/index.json"
